version: '0.1'
# Will search from these documents, item at first position takes higher priority 
document_dirs:
- C:\Users\zlzk\Documents\GitHub\zhongpengqun.github.io\docs
- D:\zhny-notes
# Files with these extensions will be token account in
extensions:
- txt
- md
- properties
exclude:
- /Users/vzhong/suoha/materials/*

