apiVersion: v1
kind: Service
metadata:
  name: hello-docker-backend
  labels:
    app: hello-docker-backend
spec:
  ports:
  - port: 8888
    protocol: TCP
  clusterIP: None
  selector:
    app: hello-docker-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-backend
  labels:
    app: hello-docker-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-docker-backend
  template:
    metadata:
      labels:
        app: hello-docker-backend
    spec:
      containers:
      - name: hello-docker-backend
        image: hello-docker-backend
