apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: cicd-lab
build:
  artifacts:
  - image: dockerfile-image
    context: project/test
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - hello/docker/backend/deployment.yaml
  - project/test/deployment.yaml
